### ISSUE TITLE
change users to mongodb instead of mysql

### ISSUE THREAD

**Issue by kwokwilliam** [kwokwilliam/questionqueue#7]

**Comment by kwokwilliam** [comment]
Will require 

- [ ] Changing userid to bson object type instead of int64
- [ ] Recreating entire mysql store to mongo

**Comment by bryoco** [comment]
When retrieving a `teacher`, `teacher.ID` will be an `ObjectID` string.
Inserting/Creating a new teacher does not require an ID.
See `src/db/mongostore.go:176`

**Comment by kwokwilliam** [comment]
I realize that you are working on the part that inserts teachers so I will remove that part from my code. I mistakenly put that because it was in my original gateway.

**Comment by kwokwilliam** [comment]
I'll look it over more later.
